spring.application.name=training-be-senang-pay-01

# Server Config
server.port=8080
server.servlet.contextPath=/${spring.application.name}

# Datasource Config
spring.datasource.url=jdbc:postgresql://localhost:5432/training_senang_pay?ApplicationName=${spring.application.name}
spring.datasource.username=postgres
spring.datasource.password=postgres

# HikariCP Config
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000

# JPA Config
spring.jpa.hibernate.ddl-auto=none

# Liquibase Config
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/master.changelog.yaml
#spring.liquibase.label-filter=sit

# Custom JDBC Logging Config - Disable this on production
decorator.datasource.enabled=true
decorator.datasource.p6spy.log-format=%(currentTime)|%(executionTime)|%(category)|connection%(connectionId)|%(sqlSingleLine)

# Distributed Lock Configuration
distributed-lock.enable=true
distributed-lock.redis-lock-type=pub_sub_lock
distributed-lock.registry-key=${spring.application.name}:
distributed-lock.release-time-duration=180s
distributed-lock.create-va-waiting-time-duration=120s
