spring.application.name=training-be-senang-pay-01

# Server Config
server.port=8282
server.servlet.contextPath=/${spring.application.name}

# KMS Aliyun Config
kms-aliyun.client-config.protocol=https
kms-aliyun.client-config.endpoint=kst-idy66987e606cdy6dlhgz.cryptoservice.kms.aliyuncs.com
kms-aliyun.client-config.client-key-content={"KeyId":"KAAP.dd9d3146-25b6-4d88-af25-0055a28c5f4f","PrivateKeyData":"MIIJwwIBAzCCCY8GCSqGSIb3DQEHAaCCCYAEggl8MIIJeDCCBC8GCSqGSIb3DQEHBqCCBCAwggQcAgEAMIIEFQYJKoZIhvcNAQcBMBwGCiqGSIb3DQEMAQYwDgQIEYkvVU/Z8UQCAggAgIID6Nxzn2y1eM9naP8d6wJKXzwpG81+Mjm0I5BTxQdJuWw/9a4ajGpWdCgw317wrc7YaZdi5nIMOoNqfA4VyBbXDIWPay3JMchzgv14ctHNJJ1sFcU6+qERcOEcQVAXtkozZou7KCE3lHCsZewU4CwYk2IxKF5tKeykebtFVThq8e6hRJiDgIV1GEwpVs4TEcyC3UNeipN0L0PymSBLprBKmicHq7HnIc4gZqQeL7OLuvGdjB0BtMCuZW8WsVRbhghWIj1SQYYYX9rgrBo/CSGKN+dH+Dn3HyG07jqyETE6K3ukPHqKxj1Gky65mAvMWZNgbDPK9QY74UDT3jWjia6QopmF0m0OcdFXxlSRmYB1E231bFN1bsDNYDvGvYT00yYfUbYyaDLX8aao64Z49Yd5obsXoJnHA4QCCYs6PsgB2/lmH/vj7dcyMzccWlz6mFfnsWhcaJOHenhMSVgPbUxYHCf3W53vYui19SuJPW3X84RoaFIUXxwPA0ymJbK2N93rTbofFI5wJkQyQT39mDGnsrPXO+XQWsdRxpJqUEunEb5QVd4PpJpALmEWADG2e24ImJtQ6PUg+pN6Q33kFY+CpIiUomipGLdFM7vnoskt0cLCTKrkCVd0FeunySXRUnByv0fqv4xkysIe6lamppNlMHuPAGjV0Ld+QEZmD/xKeTbLu/FHuz4FpkYBy07ZbKNImdiVV/YI/Ar3BukB1mU8RriNDgaO7lIk7CEd4Lcr7A9Klxm9uOoTFPdLrTPfJb4P6VCR9Ay69f+IFBKaVs5eJVr6fV+TFldvqJ96/jYWr4eJxTmbfM5hOZUdNx245cWUUS6EYo39Fzny+pQQVMOigPp76vs8NVqBnFWgvNfEiKo6VZFZQFPy8ePOLFY2PHnBBrTMF/fUYo/7jxJH6JEdH0THu5RqCjFgshHvrgDUBdlZx9HBoKKIw9PGE1mGlE309MWzENt3fd2JqiDv4a9snGYhVVPfUHi60+k/m0CevVOkwnW98fCw5IYg9OLuenEK7jQWgFrHoyT80m0ap0x5qf5ljFAZ8EVOvGrC8ID93rpC/DM5wdlIEaArkz4/JCOempW98ipXyYMOvnQ8VWJ1bYpyJ+Pu3QIHXkd/QEzIIvNQ74bY9zKcaNQ7h0s9jfUySrhx2uyeWy1uHGeo4j/Fdb/AQTiQtBj6edEoX1PkzovU7S31BK8E9pb4jBgrzBKl2wBHZywYoEYOSABHIX3y9woej54No67e2fvik/AbKci3EOeYjd475AvGUNx7pvWrJLrx3tusBeJG/+EMPPoM07f7FY9C8r5FCWNWNhyuNMM+LdzmjPhOWzwwggVBBgkqhkiG9w0BBwGgggUyBIIFLjCCBSowggUmBgsqhkiG9w0BDAoBAqCCBO4wggTqMBwGCiqGSIb3DQEMAQMwDgQILmNHRU5vKp4CAggABIIEyNPUMPgdumGrl1PZfl7TGxi1+vTZjDgtV6F49QSyIHaJqcZz1SBz67Q3CeZll+sVUUsARGuEgHAN4U6giJv8AIcIkFgtMfV2JyjIiwyXyzZu37T69xw8Ch+LZymh9Cj/N6T2CmFF+07TdbENmk55ZQa72e/08sOacTWy3Izyya6oT9KXNilJrNC/E+RZ3Tzyh4Q248WYefXHkPEOJx6+v0D3JGVug3eaGXkd3gT/+zpkHh6BsaSOFdXIsNefSVdc+e0Zo0uEsnBN+0oDc0ihScCh9Ywly9NXVN9u+cQfTRSTqutG5H6wXXkxPxqGkf/gbhHEwIE2es/ExA4MF9PrqLh6HSrvHZsbQPzoQ1e0228H80iGYT4JhciQBlnP4BBaQ5ksQaRnSUWN9S2OgpAIQnBgBFZ+E7NkMlM9XXKwRaZON8CO2L18OJUq+AAh/eG27LDDcLNoPYSiqBHIfPSS9+4TMqKrAZKkkRyS7CMP34HMLsUwQnMhsQc0iWpaUprW/nKfUTxI06ip6iNrBgIp1QHScFmoHqLSpFeaAk+QAqAfIyl3m4Ebsyk/qgyllKuvFmwGQ7ThMqTU5aMsoiNONkDzBdcKugo7k7kYplaI0c07LlYzfD+z4MARsvrfEw0Q4Btvn+KXN1MVGAHI2y1I0KrsyhO+F0TMj0IAnK5LdeNE90a72Yp23OK/HGObKBZ0tRKl7xfr2pOZf9Hvqn/084tf8/lKsbnKyOXVZQJyI6dSxLxMdeaAIKpiolv6XHlsX0yHB9hvTnbeDK9h3N1IVYKP3c8ymTW2Krwk2sQbq3+c0fsQedFbc55yuJvc6myDepeV8ZtlOdNzFItMiS1Eigqx715kExSLACP8673EQwVp/B0v8CsdN0GX9mnyyKaEhEgUNRSmwBKfRU7Z5jilqpbnNqXK6kYVQUfuvuZvmPcRUGbaIGXMFh7SZSxNtiuBmdSg48Tu/xUIZlo0UhNIf60ED8aorSq3sF9FZi6SYg8azwCoRXxdQ/OQfQwrkBi4yXDJqAyMqP39MdgRT4bbh8ALZEP/0prQOF9iRXFU3MADdtyJthSZ9sMJSlefm9a7g2Yqoqcj6cBIsVpbU3Ru91xT08uHxC2nW49edouF8PyKNPFxzOWpdq3xmkNrmnU88hIrYB2LSY3xEPrg/zazlhHnvZnCfXW5CElLFlta4b86YpGADlSTI+keiewrPVPIj+FW5zmphcjVasfDstUD95DUajcgetcr/9II0J/ZDNvlcxg0HsBreY0rlutd0hlSW6cv4J4gxYkDp6+Y3CAeddwm82jniy9/gGczR+HHU5dqQj6bwgieDlobAfgWnraR3AZ06Ky6s2HsVB7t9opFzddkO+neS4tLPflvBx2m64LtjH17qQbQAJfFuK9pn05eLLYtS1VH4J6vdPaQEFgzXWAlJvtr9ttXq3xlbmq1oT9wg8wqro7nmx/xaWzvECM/heOW2DKQmPkKJdoaBg9LRYJ9aCopT/znv095nzFVOy9k9xwIRypu0brMMfLZ3c92D6mGwrrb6VPbtKnhYTF7LRmylLI79oehU4SSvesXXGjvnOHsViKJ7+hzldCwc40LAlo5OQ9g4Lf4KdlgMqO9mDMSZ9EZ8VD/9zElMCMGCSqGSIb3DQEJFTEWBBSu2BFVUTF2aBG4hZieMtc8UVG+yjArMB8wBwYFKw4DAhoEFDpkfU50FpxyspSRtO3ANI/FLKJXBAgK/K/zKxaACw=="}
kms-aliyun.client-config.client-key-pass=6d359f4c41423a48c6480f4421919746
kms-aliyun.client-config.ca-cert-content=-----BEGIN CERTIFICATE-----\n\
MIIDuzCCAqOgAwIBAgIJALTKwWAjvbMiMA0GCSqGSIb3DQEBCwUAMHQxCzAJBgNV\n\
BAYTAkNOMREwDwYDVQQIDAhaaGVKaWFuZzERMA8GA1UEBwwISGFuZ1pob3UxEDAO\n\
BgNVBAoMB0FsaWJhYmExDzANBgNVBAsMBkFsaXl1bjEcMBoGA1UEAwwTUHJpdmF0\n\
ZSBLTVMgUm9vdCBDQTAeFw0yMTA3MDgwNjU1MjlaFw00MTA3MDMwNjU1MjlaMHQx\n\
CzAJBgNVBAYTAkNOMREwDwYDVQQIDAhaaGVKaWFuZzERMA8GA1UEBwwISGFuZ1po\n\
b3UxEDAOBgNVBAoMB0FsaWJhYmExDzANBgNVBAsMBkFsaXl1bjEcMBoGA1UEAwwT\n\
UHJpdmF0ZSBLTVMgUm9vdCBDQTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC\n\
ggEBAM99IVpxedcGYZVXXX4XZ+bYWw1gVD5Uli9kBrlq3nBT8c0b+4/1W4aQzr+S\n\
zBEWMrRZaMH3c5rV63qILyy8w4Gm2J0++nIA7uXVhpbliq6lf6p0i3cKpp+JGCbP\n\
kLvOpONrZ4an/htNE+vpfbsW3WcwcVbmZpQyuGIXIST8iyfTwckZSMkxAPW4rhMa\n\
QtmQcQiWaJsR0WJoqP7jXcHZobYehnUlzi/ZzdtmnkhTjz0+GvX9/1GBHCyfVEOO\n\
a0RiT5nEz55xWahZKbj+1nhmInbc7BUqfhz/mbQjtk5lAsJpA8JrbukRhTiAMbj9\n\
TqUqLe/meEVdjtD6wWsaZoSeoucCAwEAAaNQME4wHQYDVR0OBBYEFAVKzUR5/d6j\n\
nYM/bHlxURkGhe2EMB8GA1UdIwQYMBaAFAVKzUR5/d6jnYM/bHlxURkGhe2EMAwG\n\
A1UdEwQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAMCxpkV/KPuKVOBsT4yYkeX1\n\
Q7IQQoICOAkZOkg7KEej4BJpW2Ml121aFScKxdnRcV2omr48K+GQt/mPNAXgf3k2\n\
eKQce7xmBwntRplDJFrzdZPBdjel4i62JoWlaTejht2L5ano+x3a3keqF0GoOnn0\n\
StwpG2xa0S6RmyNFiMugwDBCtSCJAJKr8yAbO+hoe1lQR0M78dy8ENteC/BXuAks\n\
cktoG0/ryX9EqE9xQ2Do3INDq2PxIuA9yPvZ1eV3xa3bd1u+02feGIrtc9cJ5chf\n\
vUk5tbgg58NVXrg29yE5eq3j2BErUlAs2LB/Bt/Jhkekvp7qR42btJj+/zQnDSw=\n\
-----END CERTIFICATE-----\n\
\n\
-----BEGIN CERTIFICATE-----\n\
MIID4zCCAsugAwIBAgIJAOhU6JWRIW3kMA0GCSqGSIb3DQEBCwUAMHQxCzAJBgNV\n\
BAYTAkNOMREwDwYDVQQIDAhaaGVKaWFuZzERMA8GA1UEBwwISGFuZ1pob3UxEDAO\n\
BgNVBAoMB0FsaWJhYmExDzANBgNVBAsMBkFsaXl1bjEcMBoGA1UEAwwTUHJpdmF0\n\
ZSBLTVMgUm9vdCBDQTAeFw0yMzAzMTUwNjU1MjNaFw00MzAzMTAwNjU1MjNaMIGF\n\
MQswCQYDVQQGEwJDTjERMA8GA1UECAwIWmhlSmlhbmcxETAPBgNVBAcMCEhhbmda\n\
aG91MRAwDgYDVQQKDAdBbGliYWJhMQ8wDQYDVQQLDAZBbGl5dW4xLTArBgNVBAMM\n\
JFByaXZhdGUgS01TIGFwLXNvdXRoZWFzdC01IFNlY29uZCBDQTCCASIwDQYJKoZI\n\
hvcNAQEBBQADggEPADCCAQoCggEBAMLGCl7+MNU2GemCj7l4+f8937kITZdRnnJM\n\
+TlcBx+TDB24fsy4qV1rPc3PX5t/l+ZGqh2UCUviNZwhkflAVjf/nSOJbgCZh8f1\n\
BXjsKiYSoGHEKt7SYipZ+Ihagw79L3xgusGq9vEgByvuAqbDQ3m7wPI8JjreEq7M\n\
xXzPG+YHOMN3+IEj8jHmeIGGBaBHp+hOpc6dknJq4iNSEmFmauO+KTQTvMva6VAd\n\
c8xenY9pJs8unP2L6hlkEwb1m7oOH81pA9a9cdqUNUjj7+BhCjSkOkWWwche6lUY\n\
OesO8kB9Mp/n+0s2VmQiFi2fuv9B0N5KxZ7fx6e9LDcvwwqkJ5MCAwEAAaNmMGQw\n\
HQYDVR0OBBYEFMzjafFC2ZOhKDYFAE76WNDbK5ajMB8GA1UdIwQYMBaAFAVKzUR5\n\
/d6jnYM/bHlxURkGhe2EMBIGA1UdEwEB/wQIMAYBAf8CAQAwDgYDVR0PAQH/BAQD\n\
AgGGMA0GCSqGSIb3DQEBCwUAA4IBAQAVq8uSuHNgfAO93mSrLBM8epuYH3VzIZE0\n\
5GB9TvcafZZx6k6LASfuNO1VMAjltL0qUWPPVc/7InUW5Y1c9JEEFClvPOEnpyZx\n\
XqNq2vKDqJy1fmPQvLO5wpRHI7s62Gzc1cteWw9SYUBnZqBJXovzGVRJxmaDLwDx\n\
TofXUYZ7NFvX0VPB4zSO0XyNFFrK3kkVTod/U1mkvwZLOlJW62rDkbGpaAiNhdrQ\n\
2EuB7et/cVV7k8LR9hMmyOQ+41YvwpTeu3qb6baY2dGg+nnVaKbG2xG8Rku7dyho\n\
8+PeaIvrSfrcNHeXp8xh/RqqrBZD6oJxwF0adJy/bjS1qtkZsIHQ\n\
-----END CERTIFICATE-----
